import { missionPageData } from "../mission/mission.mock";
import type { PaymentData } from "./payment.types";

export const paymentMockData: PaymentData = {
  user: {
    name: "김철수",
    score: 88,
    carbonReduction: 12.4,
    points: 6300,
    balance: 128450,
    monthlyUsage: 41200,
  },
  walletMissing: false,

  categories: [
    { id: "all", label: "전체" },
    { id: "fuel", label: "주유/충전" },
    { id: "parking", label: "주차장" },
    { id: "wash", label: "세차" },
    { id: "maintenance", label: "정비" },
    { id: "store", label: "편의점" },
    { id: "cafe", label: "카페" },
  ],

  products: [
    {
      id: 1,
      name: "GS칼텍스 5,000원 주유권",
      price: 4500,
      originalPrice: 5000,
      category: "fuel",
      image: "https://picsum.photos/seed/fuel/400/300",
      discountLabel: "10%",
    },
    {
      id: 2,
      name: "모두의주차장 3,000원 할인권",
      price: 2400,
      originalPrice: 3000,
      category: "parking",
      image: "https://picsum.photos/seed/parking/400/300",
      discountLabel: "20%",
    },
    {
      id: 3,
      name: "컴인워시 노터치 세차권",
      price: 12000,
      originalPrice: 15000,
      category: "wash",
      image: "https://picsum.photos/seed/wash/400/300",
      discountLabel: "20%",
    },
    {
      id: 4,
      name: "오토오아시스 엔진오일 교환권",
      price: 45000,
      originalPrice: 55000,
      category: "maintenance",
      image: "https://picsum.photos/seed/repair/400/300",
      discountLabel: "18%",
    },
    {
      id: 5,
      name: "CU 3,000원 금액권",
      price: 2700,
      originalPrice: 3000,
      category: "store",
      image: "https://picsum.photos/seed/cu/400/300",
      discountLabel: "10%",
    },
    {
      id: 6,
      name: "스타벅스 아메리카노 T",
      price: 4050,
      originalPrice: 4500,
      category: "cafe",
      image: "https://picsum.photos/seed/coffee/400/300",
      discountLabel: "10%",
    },
    {
      id: 7,
      name: "S-OIL 10,000원 주유권",
      price: 9200,
      originalPrice: 10000,
      category: "fuel",
      image: "https://picsum.photos/seed/soil/400/300",
      discountLabel: "8%",
    },
    {
      id: 8,
      name: "아이파킹 1시간 주차권",
      price: 3200,
      originalPrice: 4000,
      category: "parking",
      image: "https://picsum.photos/seed/iparking/400/300",
      discountLabel: "20%",
    },
    {
      id: 9,
      name: "투썸플레이스 조각케익 세트",
      price: 8900,
      originalPrice: 10500,
      category: "cafe",
      image: "https://picsum.photos/seed/cake/400/300",
      discountLabel: "15%",
    },
  ],

  recentHistory: [
    {
      id: 1,
      title: "GS25 편의점",
      date: "2026.03.31",
      amount: 4800,
      type: "pay",
      category: "편의점",
    },
    {
      id: 2,
      title: "스타벅스 커피 쿠폰",
      date: "2026.03.30",
      amount: 3900,
      type: "pay",
      category: "카페",
    },
    {
      id: 3,
      title: "리워드 스토어 상품권",
      date: "2026.03.29",
      amount: 12000,
      type: "pay",
      category: "쇼핑",
    },
    {
      id: 4,
      title: "현대해상 보험료 선결제",
      date: "2026.03.28",
      amount: 50000,
      type: "pay",
      category: "보험",
    },
    {
      id: 5,
      title: "안전운전 미션 보상",
      date: "2026.03.27",
      amount: 1200,
      type: "earn",
      category: "미션",
    },
  ],

  pointHistory: [
    {
      id: 1,
      title: "3월 안전운전 보너스 적립",
      date: "2026.03.25",
      amountText: "+2,450",
      type: "earn",
    },
    {
      id: 2,
      title: "GS칼텍스 주유권 구매",
      date: "2026.03.22",
      amountText: "-4,500",
      type: "use",
    },
    {
      id: 3,
      title: "탄소 절감 미션 달성",
      date: "2026.03.15",
      amountText: "+1,200",
      type: "earn",
    },
    {
      id: 4,
      title: "신규 가입 축하 포인트",
      date: "2026.03.01",
      amountText: "+5,000",
      type: "earn",
    },
  ],

  coupons: [
    {
      id: 1,
      name: "스타벅스 아메리카노 10% 할인",
      expiry: "2026.04.15",
      discount: "10%",
      category: "카페",
      used: false,
    },
    {
      id: 2,
      name: "GS25 1,000원 금액권",
      expiry: "2026.04.10",
      discount: "1,000원",
      category: "편의점",
      used: false,
    },
    {
      id: 3,
      name: "S-OIL 3,000원 주유 할인",
      expiry: "2026.04.20",
      discount: "3,000원",
      category: "주유/차량",
      used: false,
    },
    {
      id: 4,
      name: "넷플릭스 1개월 구독 지원",
      expiry: "2026.04.05",
      discount: "5,000원",
      category: "생활",
      used: true,
    },
  ],

  historySummary: {
    earnedPoint: 2450,
    usedPoint: 4500,
    extraPoint: 3200,
  },

  missionSummary: missionPageData.summary,
  missions: missionPageData.missions,
};
